apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-green
  name: webapp-green
spec:
  containers:
  - image: kodekloud/webapp-color
    name: webapp-green
    args: ["--color=green"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
